language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
      addons:
        apt:
          packages:
            - dos2unix
    - env: TARGET=thumbv7em-none-eabihf
      rust: nightly

before_install: set -e

install:
  - sh ci/install.sh

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - develop
    - master
