language: rust

matrix:
  include:
    - env: TARGET=thumbv7em-none-eabi
      rust: nightly
      addons:
        apt:
          packages:
            - gcc-arm-none-eabi

before_install: set -e

install:
  - sh ci/install.sh

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - develop
    - master
