[package]
name = "f3_eva"
version = "0.1.0"
authors = ["Roma Sokolov", "Alexander Zhuravlev"]

[dependencies]

[profile.dev]
panic = "abort"
opt-level = "s"
lto = false
codegen-units = 1
incremental = false

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.1.0"

[dependencies.stm32f30x-hal]
git = "https://github.com/copterust/stm32f30x-hal.git"

[dependencies.stm32f30x]
version = "0.6.0"
features = ["rt"]

[dependencies.panic-abort]
version = "0.1.1"

[dependencies.nb]
version = "0.1.0"

[dependencies.cortex-m]
version = "0.4.3"

[dependencies.cortex-m-rt]
version = "0.4.0"

[dependencies.mpu9250]
version = "0.1.0"
git = "https://github.com/japaric/mpu9250.git"
