cargo-features = ["edition", "rename-dependency"]

[package]
name = "f3_eva"
version = "0.1.0"
authors = ["Roma Sokolov", "Alexander Zhuravlev"]
edition = '2018'


[profile.dev]
panic = "abort"
debug = true
opt-level = "s"
lto = true
codegen-units = 1
incremental = false

[profile.release]
panic = "abort"
opt-level = "z"
codegen-units = 1
debug = false
lto = true
incremental = false # nalgebra

[dependencies]
nb = "0.1.1"
cortex-m = "0.5.6"
stm32f30x = {version = "0.7.0", features = ["rt"]}
mpu9250 = "0.6.2"
libm = "0.1.2"

[dependencies.rt]
version = "0.5.2"
package = "cortex-m-rt"

[dependencies.madgwick]
git = "https://github.com/copterust/madgwick"
rev = "13771fdb2cbd70557d43176914b070dd5186a445"

[dependencies.ehal]
features = ["unproven"]
version = "0.2.1"
package = "embedded-hal"

[dependencies.hal]
version = "0.8.1"
package = "alt-stm32f30x-hal"

[dependencies.nalgebra]
default-features = false
version = "0.16.0"

[dependencies.dcmimu]
version = "0.1.0"
git = "https://github.com/copterust/dcmimu"
rev = "32209dcf52884dd98046fc4b82c2a0a5ac44ff71"

[features]
default = ["usart1"]
usart1 = []
usart2 = []
