cargo-features = ["edition", "rename-dependency"]

[package]
name = "f3_eva"
version = "0.1.0"
authors = ["Roma Sokolov", "Alexander Zhuravlev"]
edition = '2018'

[profile.dev]
panic = "abort"
debug = true
opt-level = "s"
lto = false
codegen-units = 1
incremental = false

[dependencies]
panic-abort = "0.2.0"
nb = "0.1.1"
cortex-m = "0.5.4"
stm32f30x = {version = "0.7.0", features = ["rt"]}
mpu9250 = "0.2.4"

[dependencies.rt]
version = "0.5.1"
package = "cortex-m-rt"

[dependencies.madgwick]
git = "https://github.com/little-arhat/madgwick"
rev = "30add4b09b4e3e8a0b4a7b04d8154c7751d0eaa0"

[dependencies.ehal]
features = ["unproven"]
version = "0.2.1"
package = "embedded-hal"

[dependencies.hal]
version = "0.6.1"
package = "alt-stm32f30x-hal"
