[package]
name = "f3_eva"
version = "0.1.0"
authors = ["Roma Sokolov", "Alexander Zhuravlev"]

[dependencies]

[profile.dev]
panic = "abort"
debug = true
opt-level = "s"
lto = false
codegen-units = 1
incremental = false

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.1"

[dependencies.stm32f30x-hal]
git = "https://github.com/copterust/stm32f30x-hal.git"
rev = "cc2483b046f28012a15742f762dde717a2843255"

[dependencies.stm32f30x]
version = "0.7.0"
features = ["rt"]

[dependencies.panic-abort]
version = "0.1.1"

[dependencies.nb]
version = "0.1.1"

[dependencies.cortex-m]
version = "0.5.2"

[dependencies.cortex-m-rt]
version = "0.5.1"

[dependencies.mpu9250]
git = "https://github.com/copterust/mpu9250.git"
rev = "d6fbfd549dcd3627c4aa08d2d8db3da15e9f6ac9"
